alert("A Zebra licked a DVD");
alert("Angry people need hugs or sharp objects");
alert("Banana suicide");
alert("Blue is greener than purple for sure");
alert("Booty shakin all day everyday");
alert("Come to the dark side. We have cookies");
alert("Did my sarcasm hurt your feels? Get over it");
alert("Do not disturb, evil genius at work");
alert("Dont mess with me! I have a stick");
alert("Eat your foot");
alert("Even my issues have issues");
alert("Expelled is on Netflix");
alert("Fat kids are harder to kidnap");
alert("Get high, climb a tree");
alert("Go pre-order Handwritten");
alert("I am pretending to be a tomato");
alert("I am so blue Im greener than purple");
alert("I cant remember if its time for your medication or mine");
alert("I do not go out side, why should I be giving a shoutout to the sun");
alert("I got two pickles");
alert("I hate the green flashing light");
alert("I know kung fu and 50 other dangerous words");
alert("I like to eat my toes");
alert("I might drive into all the malls");
alert("I scream you scream we all scream for ice scream");
alert("I stepped on a Corn Flake, now Im a Cereal Killer");
alert("I use sarcasm instead of punching you in the face");
alert("I want a yummy little puppy");
alert("Im addicted to youtubers");
alert("Im feeling a bit Frantastic");
alert("Im on a seafood diet. I see food, and I eat it");
alert("Internet kids never sleep");
alert("Is your eye brow game strong");
alert("Joe sugg is a genius");
alert("Lady Gaga is gonna be in American Horror Story");
alert("Life is like a box of chocolates");
alert("Love your enemies, it makes them angry");
alert("May the odd be ever in your favor");
alert("Miranda Is the real queen! Jk haha lol");
alert("My eraser will kick your erasers ass");
alert("My mom said that I am cool because I don’t do drugs.");
alert("Never put a cat on your head");
alert("Never set yourself on fire");
alert("On a scale from one to ten what is your favourite colour of the alphabet");
alert("Penguins are the only thing I don’t have");
alert("Pikachu I choose you");
alert("Save a drum, bang a drummer");
alert("Save a horse, ride a cowboy");
alert("Save a tree, eat a beaver");
alert("Save water, drink beer");
alert("School is lame");
alert("Sheep are just demented sticks of candy floss");
alert("The banana has legs");
alert("The koala jumped over a turtlet");
alert("They say that hard work never hurt anyone but why take the risk");
alert("This is Bob. Bob likes you. Bob likes sharp things. I suggest you run from Bob.");
alert("Tomorrow has been cancelled due to lack of interest");
alert("Were all gonna die, but I have a helmet");
alert("When life gives you lemons, chuck them at people you hate");
alert("Why is that dog meowing");
alert("You are my queen slay me");
alert("You do you and I do me");
